sudo: required
services:
  - docker

before_install:
  - docker build -t ryleysill/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ryleysill/client-test npm test


after_success:
  - docker build -t ryleysill/complex-client ./client
  - docker build -t ryleysill/complex-nginx ./nginx
  - docker build -t ryleysill/complex-worker ./worker
  - docker build -t ryleysill/complex-server ./server

  - docker login -u="$DOCKER_ID" -p="$DOCKER_PASSWORD"
  - docker push ryleysill/multi-client
  - docker push ryleysill/multi-nginx
  - docker push ryleysill/multi-server
  - docker push ryleysill/multi-worker