sudo: required
services:
  - docker

before_install:
  - docker build -t ryleysill/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ryleysill/client-test npm test


after_success:
  - docker build -t ryleysill/complex-client ./client
  - docker build -t ryleysill/complex-nginx ./nginx
  - docker build -t ryleysill/complex-worker ./worker
  - docker build -t ryleysill/complex-server ./server

  - docker login -u="$DOCKER_ID" -p="$DOCKER_PASSWORD"
  - docker push ryleysill/complex-client
  - docker push ryleysill/complex-nginx
  - docker push ryleysill/complex-server
  - docker push ryleysill/complex-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: complex
  env: Complex-env
  bucket_name: elasticbeanstalk-us-west-1-416912674609
  bucket_path: complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY